# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c84e0e187975d2fd27a7c9839bfe9a630dea859e2ec2ed85b26edf0b7b18e830be4a19b273edd1349af1475591a3cd1eff9b8fcfd4364bb33069703456375f14

test:
  secret_key_base: 556540175e4818f09b9409eef218b5b7392596702e8bb964b627d00fc267101cfb104991daf2cfd57a0a629d49ce444c7067aeba8cb2a54e6ca1c0303c8d4be8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
